/* eslint-disable quote-props */

const atRuleEmptyLineBefore = require('./rules/at-rule-empty-line-before.js');
const atRuleNoUnknown = require('./rules/at-rule-no-unknown.js');
const declarationBlockNoDuplicateProperties = require('./rules/declaration-block-no-duplicate-properties.js');
const declarationBlockPropertiesOrder = require('./rules/declaration-block-properties-order.js');

module.exports = {
	rules: {
		'at-rule-empty-line-before': atRuleEmptyLineBefore,
		'at-rule-name-case': 'lower',
		'at-rule-no-unknown': atRuleNoUnknown,
		'at-rule-no-vendor-prefix': true,
		'block-closing-brace-newline-after': 'always',
		'block-closing-brace-newline-before': 'always',
		'block-no-empty': true,
		'block-no-single-line': true,
		'block-opening-brace-newline-after': 'always',
		'block-opening-brace-space-before': 'always',
		'color-hex-case': 'upper',
		'color-no-invalid-hex': true,
		'comment-no-empty': true,
		'comment-whitespace-inside': 'always',
		'declaration-bang-space-after': 'never',
		'declaration-bang-space-before': 'always',
		'declaration-block-no-duplicate-properties': declarationBlockNoDuplicateProperties,
		'declaration-block-no-ignored-properties': true,
		'declaration-block-no-redundant-longhand-properties': true,
		'declaration-block-no-shorthand-property-overrides': true,
		'declaration-block-properties-order': declarationBlockPropertiesOrder,
		'declaration-block-semicolon-newline-after': 'always',
		'declaration-block-semicolon-space-before': 'never',
		'declaration-colon-space-after': 'always-single-line',
		'declaration-colon-space-before': 'never',
		'font-weight-notation': 'numeric',
		'indentation': 'tab',
		'keyframe-declaration-no-important': true,
		'length-zero-no-unit': true,
		'max-empty-lines': 1,
		'max-line-length': 120,
		'max-nesting-depth': 4,
		'no-indistinguishable-colors': [true, { threshold: 3 }],
		'no-invalid-double-slash-comments': true,
		'no-missing-end-of-source-newline': true,
		'no-unknown-animations': true,
		'property-case': 'lower',
		'property-no-unknown': true,
		'property-no-vendor-prefix': true,
		'selector-list-comma-newline-after': 'always',
		'selector-list-comma-newline-before': 'never-multi-line',
		'selector-max-empty-lines': 0,
		'selector-max-specificity': '0,3,3',
		'shorthand-property-no-redundant-values': true,
		'string-quotes': 'double',
		'stylelint-disable-reason': 'always-before',
		'unit-blacklist': ['cm', 'pt', 'ch', 'mm', 'in', 'pc', 'ex'],
		'unit-case': 'lower',
		'value-list-comma-newline-after': 'always-multi-line',
		'value-list-comma-newline-before': 'never-multi-line',
		'value-list-comma-space-after': 'always-single-line',
		'value-list-comma-space-before': 'never',
		'value-list-max-empty-lines': 0,
	},
};
